apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/sqlserver-pv2/